MvcApplication1/Models/Galeria.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Security;
using System.Linq;
using System.Web;



namespace Galeria
{
    public class Zdjecie_c
    {
        [Key]
        [Required]
        public int Id_z { set; get; }
        [Required]
        public string Wl { set; get; }
        [Required]
        public string Tytul { set; get; }
        [Required]
        public byte[] Zdjecie { set; get; }
        public DateTime Data_W { set; get; }
        public virtual ICollection<Komentarz_c> Komentarze { set; get; }
    }


    public class Komentarz_c
    {
        [Key]
        [Required]
        public int Id_k { set; get; }
        [Key]
        [Required]
        [ForeignKey("Zdjecie_c.Id_z")]
        public int Id_z { set; get; }
        public DateTime Data_w { set; get; }
        public string Komentarz { set; get; }
        public virtual Zdjecie_c Zdjecie { set; get; }

        
    }
    public class UsersContext : DbContext
    {
        public UsersContext()
            : base("DefaultConnection") //domyślne połączenie z bazą skonfigurowane w pliku web.config
        {
        }

        public DbSet<UserProfile> UserProfiles { get; set; }
    }

    [Table("UserProfile")]
    public class UserProfile
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        public string UserName { get; set; }
    }

    public class RegisterExternalLoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        public string ExternalLoginData { get; set; }
    }

    public class LocalPasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ExternalLogin //np logowanie przez FB
    {
        public string Provider { get; set; }
        public string ProviderDisplayName { get; set; }
        public string ProviderUserId { get; set; }
    }
}

MvcApplication1/Controllers/GaleriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Galeria;

namespace Galeria.Controllers
{
    public class GaleriaController : Controller
    {
        //
        // GET: /Galeria/

        public ActionResult Index()
        {
            return View("Index");
        }
        public ActionResult Zdjecie(int Id = 0) //jeżeli nie damy to zera, to będzie błąd serwera przy wyswietlaniu strony
        {
            Zdjecie_c is_z = new Zdjecie_c();
            return View("Zdjecie", is_z);
        }
        public ActionResult Photos()
        {
            return View("Photos");
        }
        public ActionResult Login()
        {
            return View("Login");
        }
        public ActionResult Register()
        {
            return View("Register");
        }
        public ActionResult Create(int Id_z, string Wl, string Tytul, DateTime Data_w, byte[] Zdj)
        {
            Zdjecie_c nowe_z = new Zdjecie_c();
            nowe_z.Id_z=Id_z;
            nowe_z.Wl = Wl;
            nowe_z.Tytul=Tytul;
            nowe_z.Data_W = Data_w;
            for (int i = 0; i < Zdjecie.Length; i++)
            {
                nowe_z.Zdjecie[i] = Zdjecie[i];
            }
            nowe_z.Zdjecie[0] = Zdjecie[0];
            
            return View("Create");
        }
    }
}

MvcApplication1/Views/Galeria/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Index</h2>
<script type="text/javascript"> Cufon.now(); </script>

MvcApplication1/Views/Galeria/Login.cshtml
@model Galeria.LoginModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<article id="content">


    <div class="wrapper">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "Contactform" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div>
                <div class="wrapper">
                    <span>@Html.LabelFor(m => m.UserName)</span>
                    <div class="bg">
                        @Html.TextBoxFor(m => m.UserName, new { @class = "Input" })
                        @Html.ValidationMessageFor(m => m.UserName)
                    </div>
                </div>

                <div class="wrapper">
                    <span>@Html.LabelFor(m => m.Password, new { @class = "Input" })</span>
                    <div class="bg">
                        @Html.PasswordFor(m => m.Password)
                        @Html.ValidationMessageFor(m => m.Password)
                    </div>
                </div>
                <div class="wrapper">
                    <span>@Html.LabelFor(m => m.RememberMe, new { @class = "checkbox" })</span>
                    @Html.CheckBoxFor(m => m.RememberMe)
                </div>
            </div>
            
            <input class="button1" type="submit" value="Log in" />

            <p>
                @Html.ActionLink("Zarejestruj się", "Register") jeżeli nie masz jeszcze konta...
            </p>

        }
    </div>
</article>

MvcApplication1/Views/Galeria/Photos.cshtml
@{
    ViewBag.Title = "Photos";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Photos</h2>
<script type="text/javascript"> Cufon.now(); </script>

MvcApplication1/Views/Galeria/Register.cshtml
@model Galeria.RegisterModel
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<article id="content">
    <div class="wrapper">
        <h2>Contact form</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            <fieldset>
                <legend>Registration Form</legend>
                <ol>
                    <li>
                        @Html.LabelFor(m => m.UserName)
                        @Html.TextBoxFor(m => m.UserName)
                    </li>
                    <li>
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password)
                    </li>
                    <li>
                        @Html.LabelFor(m => m.ConfirmPassword)
                        @Html.PasswordFor(m => m.ConfirmPassword)
                    </li>
                </ol>
                <input type="submit" value="Register" />
            </fieldset>
        }
    </div>
</article>

MvcApplication1/Views/Galeria/Zdjecie.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Zdjecie</title>
</head>
<body>
    <div>
        @using (Html.BeginForm())
        {
            @Html.LabelFor(model => model.Tytul)
            @Html.TextBoxFor(model => model.Tytul)
            @Html.LabelFor(model => model.Zdjecie)
    <input type="file" name="Zdjecie" value=" " />
            @Html.TextBoxFor(model => model.Wl, new { hidden = "hidden", @value=""})
            @Html.TextBoxFor(model => model.Data_w, new { hidden = "hidden", @value = DateTime.Now })
    <input type="text" name="Wl" value= "" hidden="hidden" />
    <input type="submit" value="wstaw" />

        }
    </div>
</body>
</html>

MvcApplication1/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
@using System.Web.Optimization;

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <link href="~/css/reset.css" rel="stylesheet" />
    <link href="~/css/layout.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    
    <script src="~/js/jquery-1.6.js"></script>
    <script src="~/js/cufon-yui.js"></script>
    <script src="~/js/cufon-replace.js"></script>
    <script src="~/js/Vegur_300.font.js"></script>
    @*<script src="~/js/PT_Sans_700.font.js"></script>
    <script src="~/js/PT_Sans_400.font.js"></script>*@
    <script src="~/js/tms-0.3.js"></script>>
    <script src="~/js/tms_presets.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/atooltip.jquery.js"></script>
</head>
<body>
    <!--header -->
    <header>
        <div class="wrapper">
            <h1>@Html.ActionLink("Gallery COM", "Index", "Galeria", new { @id = "logo" })</h1>
            <form id="search" method="post">
                <fieldset>
                    <div class="bg"><input class="input" type="text" value="Search" onblur="if(this.value=='') this.value='Search'" onfocus="if(this.value =='Search' ) this.value=''"></div>
                </fieldset>
            </form>
        </div>
        <nav>
            <ul id="menu">

                @*<li class="active">*@<li id="p1"><a href="@Url.Action("Index", "Galeria")"><span>O galerii</span></a></li>
@*<li><span>@Html.ActionLink("O galerii", "Index", "Galeria")</span></li>*@
@*<li class="active"><a href="galeria/Index"><span>O galerii</span></a></li>*@
                <li id="p2"><a href="@Url.Action("Photos", "Galeria")"><span>Zdjęcia</span></a></li>
@*<li><span>@Html.ActionLink("Zdjęcia", "Photos", "Galeria")</span></li>*@
@*<li><a href="galeria/photos"><span>Zdjęcia</span></a></li>*@
                <li id="p3"><a href="@Url.Action("Login", "Galeria")"><span>Logowanie</span></a></li>
@*<li><span>@Html.ActionLink("Logowanie", "Login", "Galeria")</span></li>*@
@*<li><a href="galeria/login"><span>Logowanie</span></a></li>*@
            </ul>
        </nav>
        @*<div id="slider">
            <ul class="items">
                <li>
                    <img src="images/img1.jpg" alt="">
                    <div class="banner">
                        <span class="title"><span class="color2">We Have</span><span class="color1">Propositions</span><span>For Everybody</span></span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmod tempor.</p>
                        <a href="#" class="button1">Read More</a>
                    </div>
                </li>
                <li>
                    <img src="images/img2.jpg" alt="">
                    <div class="banner">
                        <span class="title"><span class="color2">Fresh Ideas</span><span class="color1">For Growing</span><span>Your Business</span></span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmod tempor.</p>
                        <a href="#" class="button1">Read More</a>
                    </div>
                </li>
                <li>
                    <img src="images/img3.jpg" alt="">
                    <div class="banner">
                        <span class="title"><span class="color2">The Best</span><span class="color1">You Can Find</span><span>On The Web</span></span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmod tempor.</p>
                        <a href="#" class="button1">Read More</a>
                    </div>
                </li>
            </ul>
        </div>*@
    </header>
    <!--header end-->
    <div>
        @RenderBody()
    </div>
    <!--footer -->
    <footer>
        <ul id="icons">
            <li class="first">Follow Us:</li>
            <li><a href="#" class="normaltip" title="Facebook"><img src="images/icon1.jpg" alt=""></a></li>
            <li><a href="#" class="normaltip" title="Twitter"><img src="images/icon2.jpg" alt=""></a></li>
            <li><a href="#" class="normaltip" title="Picasa"><img src="images/icon3.jpg" alt=""></a></li>
            <li><a href="#" class="normaltip" title="YouTube"><img src="images/icon4.jpg" alt=""></a></li>
        </ul>
        Superior.com &copy; 2011 <br>Website Template by <a href="http://www.templatemonster.com/" target="_blank">TemplateMonster.com</a><br>
        <!-- {%FOOTER_LINK} -->
    </footer>
    <!--footer end-->
    <script src="~/js/atooltip.my.js"></script>
</body>
</html>